# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
# 
include:
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
---
# include:

#   - board: nrfmicro_13
#     shield: tbkmini_left
#   - board: nrfmicro_13
#     shield: tbkmini_right
#   - board: nrfmicro_13
#     shield: [corne_left, corne_right]
#     name: ["Corne"]
#   - board: nrfmicro_13
#     shield: settings_reset
